from pydantic_settings import BaseSettings


    
DATABASE_URL: str

CLIENT_ORIGIN: str
COOKIES_DOMAIN: str = ""
FRONTEND_URL: str

FIRST_SUPERUSER_EMAIL: str
FIRST_SUPERUSER_FISCALCODE: str
USERS_OPEN_REGISTRATION: str

EMAIL_RESET_TOKEN_EXPIRE_HOURS: int
EMAILS_ENABLED: str

ACCESS_TOKEN_EXPIRE_MINUTES: int = 10
JWT_ALGORITHM: str
JWT_PRIVATE_KEY: str  = ""
JWT_PUBLIC_KEY: str

    

