version: '3.8'

services:
  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./eXtendedRingPrivacy:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge