services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: Hackathon2024
      POSTGRES_PASSWORD: Hackathon2024
      POSTGRES_DB: db_Hackathon2024
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .backend/pygres/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth_module:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8001:8000"  # Mappa la porta 8000 del container a 8000 sulla macchina locale
    environment:
      DATABASE_URL: "postgresql://Hackathon2024:Hackathon2024@postgres:5432/db_Hackathon2024"  # URL del DB PostgreSQL (utilizzando il nome del servizio come host)
    volumes:
      - .:/backend
  
  ripple_module:
    # import from crud/compose.yml
    extends:
      file: ./crud/compose.yml
      service: crud

    depends_on:
      - postgres
  
volumes:
  postgres_data:
