services:
    crud:
      image: python:3.12-slim
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      command: /bin/bash -c "pip install -r /app/requirements.txt && python /app/src/main.py"