version: "3.8"
 
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: Hackaton2024
      POSTGRES_PASSWORD: Hackaton2024
      POSTGRES_DB: Database1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # app:
  #   build: .
  #   container_name: app
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: "postgresql+psycopg2://youruser:yourpassword@db/yourdb"
  #   volumes:
  #     - .:/app
  #   command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  #   ports:
  #     - "8000:8000"

volumes:
  postgres_data: