services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: Hackaton2024
      POSTGRES_PASSWORD: Hackaton2024
      POSTGRES_DB: db_Hackaton2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
