services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: Hackathon2024
      POSTGRES_PASSWORD: Hackathon2024
      POSTGRES_DB: db_Hackathon2024
    ports:
      - "5432:5432"  # Mappa la porta 5432 del container a 5433 sulla macchina locale
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data:
